# Generated by Django 5.1.1 on 2024-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketpurchase_name_alter_event_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='pdf',
            field=models.FileField(default='events/default.jpg', null=True, upload_to='pdf'),
        ),
    ]
