# Generated by Django 5.1.2 on 2024-10-10 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketpurchase_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
