# Generated by Django 5.1.2 on 2024-10-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_organisation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inserted_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='inserted_by',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='inserted_by',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='updated_by',
        ),
    ]
